### ISSUE TITLE
Backspace key not working on Karaf console

### ISSUE THREAD

**Issue by eschizoid** [openhab/openhab-docker#30] opened 2016-09-06 03:16 UTC
When logging into the `Karaf` Console using the following command:

`docker exec -it aa51cbf7d3f6 /openhab/runtime/karaf/bin/client` the backspace key is behaving as the space key.

This is not happening when using `karaf/bin/shell`

**Comment by legacycode** [comment] 2017-01-13 20:36
I could reproduce and solve this issue. The problem is the environment variable TERM. This variable seems to be set to export TERM=xterm after attaching to the conatainer, but it is not! After running export export TERM=xterm the backsoace key works as expected in client console.

I found some other bug reports with more information. It seems to be a docker issue. Here you can find some more information:

https://github.com/dockerfile/mariadb/issues/3
https://github.com/docker/docker/pull/26461

PR #51 will solve this issue for now... maybe in the future there will be a better solution.

**Comment by cniweb** [comment] 2017-01-16 19:45
PR #51 merged, I close this issue.

**Closed by cniweb** 2017-01-16 19:45 UTC
