### ISSUE TITLE
ttyUSB lock files not removed on a container restart

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docker#195] opened 2018-09-17 20:04 UTC
Behavior:
When passing in a device to the container the OH lock files in /var/lock do not get removed. This causes OH to fail to connect to the devices on when the container restarts.

Workaround:
1. Restart the container
2. `docker exec -it /bin/bash` followed by `rm /var/lock/LCK..ttyUSB*`
3. Restart the container once again

I'm not sure if the SIGTERM is not being received by OH, Docker doesn't give OH enough time to finish shutting down, or something else broke preventing the cleanup of these lock files. I'm not even sure who/what creates the locks (OH or the OS?).

This was not a problem in OH 2.3.

Relevant forum thread: https://community.openhab.org/t/docker-serial-port-dev-xxxxx-could-not-be-opened/51541/4

**Comment by wborn** [comment] 2018-11-02 00:16
Perhaps it's caused by switching from the openHAB nrjavaserial fork to the official nrjavaserial release.

See also my comment in this [community thread](https://community.openhab.org/t/rxtx-fhs-lock-error-opening-lock-file-var-lock-lck-ttyusb0-file-exists-it-is-mine/49117/25?u=wborn).

I also tested properly shutting down OH in the container but that didn't fix the issue for me. I'll probably create a PR to fix that anyway. ;-)

**Comment by wborn** [comment] 2018-11-10 23:39
Can you test if this issue is fixed with the latest 2.4.0-SNAPSHOT build # 1420 @rkoshak? 
It contains an OH fork of the nrjavaserial library which no longer uses lock files.

**Comment by rkoshak** [comment] 2018-11-13 18:32
I just downloaded the latest snapshot image, created a new container, once it started up successfully I restarted the container and I can confirm access to the zwave and zigbee devices is no longer blocked.

Looks like you fixed it. :-)

**Comment by wborn** [comment] 2018-11-13 21:41
That's good news @rkoshak ! :smile:

**Comment by cniweb** [comment] 2018-11-18 22:32
That means we can close this issue?

**Comment by wborn** [comment] 2018-12-04 23:58
Yes it can be closed. The lock file issue was already fixed and with the latest commit it should also properly shutdown the runtime when the container is stopped.

**Closed** 2018-12-06 20:46 UTC
Labels: help wanted
