### ISSUE TITLE
Using the latest openhab 2.0.0 armhf on a PI with zwave enabled fails to connect to the Zwave stick

### ISSUE THREAD

**Issue by peterjwood** [openhab/openhab-docker#76] opened 2017-02-08 10:29 UTC
It would seem that the serial driver for the USB stick is compiled for the wrong platform, the following appears in the docker logs

```
java.lang.UnsatisfiedLinkError: /openhab/userdata/tmp/libNRJavaSerial_openhab_0/libNRJavaSerial.so: /openhab/userdata/tmp/libNRJavaSerial_openhab_0/libNRJavaSerial.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at gnu.io.NativeResource.loadResource(NativeResource.java:142)
	at gnu.io.NativeResource.inJarLoad(NativeResource.java:40)
	at gnu.io.NativeResource.loadLib(NativeResource.java:60)
	at gnu.io.NativeResource.load(NativeResource.java:28)
	at gnu.io.SerialManager.<init>(SerialManager.java:10)
	at gnu.io.SerialManager.getInstance(SerialManager.java:16)
	at gnu.io.RXTXCommDriver.<clinit>(RXTXCommDriver.java:87)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:109)
	at org.openhab.binding.zwave.handler.ZWaveSerialHandler.initialize(ZWaveSerialHandler.java:81)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:713)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by legacycode** [comment] 2017-02-10 15:58
Hi,
this is not a problem of the docker images. It seems that there is no zwave lib available for ARM architecture. I have found a lot of other posts:

https://community.openhab.org/t/64-bit-arm-serial/8493

@kaikreuzer: Do you have an idea how we can solve this? I saw a lot of solutions from you on the web.

**Comment by umiddelb** [comment] 2017-02-10 16:07
This issue here seems to be a configuration management issue, since the x86 flavour of `libNRJavaSerial.so` is shipped with armhf package.

On arm64 you need to build `libNRJavaSerial.so` from source, but you don't really want to use the current 64bit JVM on arm64 at this time.

**Comment by legacycode** [comment] 2017-02-10 16:17
@umiddelb: Thanks for your quick reply and this important information. @peterjwood: could you please provide your full docker run command or an docker-compose file?

**Comment by peterjwood** [comment] 2017-02-10 16:38
the PI is armhf 32 bit not 64, and zwave was working perfectly well with the openhab installation we have been using up to now but that was before the switch in Java engines and the project was split in to the different releases

I have followed the instructions for https://github.com/openhab/openhab-docker#starting-with-docker-mounting-a-host-directory-for-advanced-user  with a couple of corrections that I found needed applying

mkdir /opt/openhab/ && \
mkdir /opt/openhab/addons/ && \
mkdir /opt/openhab/conf/ && \
mkdir /opt/openhab/userdata/ && \
sudo chown 9001.9001 /opt/openhab -R

docker run --rm \
  --user 9001 \
  -v /opt/openhab/addons:/openhab/addons \
  -v /opt/openhab/conf:/openhab/conf \
  -v /opt/openhab/userdata:/openhab/userdata \
  openhab/openhab:2.0.0-armhf \
  sh -c 'cp -av /openhab/userdata.dist/* /openhab/userdata/ && cp -av /openhab/conf.dist/* /openhab/conf/'

docker run -t --user 9001 --name openhab --net=host -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /opt/openhab/addons:/openhab/addons -v /opt/openhab/conf:/openhab/conf -v /opt/openhab/userdata:/openhab/userdata --device=/dev/ttyACM0 -d openhab/openhab:2.0.0-armhf

Everything runs and I install the expert group of UI, add the zwave binding and set up a serial device, it is only when I then add the port /dev/ttyACM0 to the zwave settings for the serial device that I see the error above when I run "docker logs openhab" from the PI terminal

docker -it openhab /bin/bash 

Allows me to get in to the container and the device is properly set up and visible

**Comment by legacycode** [comment] 2017-02-10 16:42
Ah ok. I found the problem. Maybe it will be solved after merging PR #75.

**Comment by peterjwood** [comment] 2017-02-14 11:20
Sorry but this is not fixed by the latest version the issue is still as I listed above

**Comment by Alpha200** [comment] 2017-02-14 16:46
I have the same problem with a CUL device and the FS20 binding on my Banana Pi. The fix did not work for me, too. I tried to build the `libNRJavaSerial.so` manually and replace the existing file in the container, but it did not help. Maybe I've done something wrong, but I don't think the problem is that openHAB can't load the file because it is compiled for the wrong architecture. The exception says: 

> cannot open shared object file: No such file or directory.

 Is there maybe some mistake in the configuration?

**Comment by legacycode** [comment] 2017-02-14 19:19
hi. maybe you can try to run the openhab container as root in interactive mode with the following command for debugging. Maybe it is a permission problem:

` docker run -it --rm --net=host openhab/openhab:2.0.0-amd64 ./start.sh`

The "./start.sh" will override the "gosu openhab ./start.sh" and lets you start the container as user root.

**Comment by Alpha200** [comment] 2017-02-14 21:00
I've tested your instructions, but it throws the same exceptions. The debug output does not contain any additional information that might be relevant.

I've removed the stick from my Banana Pi and tested it with my notebook and it works without any modifications. It must therefore be an issue that appears only on the ARM architecture.

**Comment by ievans** [comment] 2017-03-19 23:54
Agreed, I see this same issue on a clean install of armhf (which is 32-bit), even with the container running as root. Confusingly, this ends up showing up as "Port /dev/ttyUSB0 does not exist" in the [error message from the zwave binding](https://github.com/openhab/org.openhab.binding.zwave/blob/27c79e6fa943d3595747c741d04e9d8f5fa8c56f/src/main/java/org/openhab/binding/zwave/handler/ZWaveSerialHandler.java#L100).

Here a snippet of the debug log output I get after the UnsatisfiedLinkError:

```
... java.lang.ExceptionInInitializerError thrown while loading gnu.io.RXTXCommDriver
... java.lang.NoClassDefFoundError: Could not initialize class gnu.io.RXTXCommDriver thrown while loading gnu.io.RXTXCommDriver
...
23:45:52.451 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:XXXXXXX' changed from OFFLINE (BRIDGE_OFFLINE): Controller is offline to OFFLINE (COMMUNICATION_ERROR): Serial Error: Port /dev/ttyUSB0 does not exist
```
And what's getting linked in is all IA-32:

```
~$ file `find /opt/openhab/ -type f -name "libNRJavaSerial*"`
/opt/openhab/userdata/tmp/libNRJavaSerial_legacy_openhab_0/libNRJavaSerial_legacy.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not stripped
/opt/openhab/userdata/tmp/libNRJavaSerial_openhab_0/libNRJavaSerial.so:               ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=408f8c31a556d731d5b438f36e9c91ec2bb69f5c, not stripped
```

**Comment by ievans** [comment] 2017-03-26 18:55
Just as an update, I can confirm this issue is isolated to the specific Java implementation bundled by the Dockerfile. I switched my fork of the Dockerfile to `openjdk-8-jre` and it works just fine (though it's a bit slower because of openjdk, I think).

**Comment by cniweb** [comment] 2017-03-26 20:14
@kaikreuzer and @legacycode is it a 32 / 64 bit armhf issue?

**Comment by kaikreuzer** [comment] 2017-03-26 21:23
Sorry, I have no clue. I don't understand how the used JVM could make any difference (unless @ievans switched from a 32bit JVM to 64-bit OpenJDK)...

**Comment by boomalien** [comment] 2017-04-25 20:06
I can also confirm this issue. I get the same error on my Pi when I try to pass /dev/ttyACM0 to the container. As workaround I installed Oracle Java8. With the Oracle JVM the Z-Wave stick works as expected.
You can check my Dockerfile here https://github.com/boomalien/rpi-openhab-oracle-java8/blob/master/Dockerfile
or pull the image from https://hub.docker.com/r/boomalien/rpi-openhab-oracle-java8/

**Comment by stephan-bury** [comment] 2017-05-10 13:09
I think the problem is, that the JVM extracts the library with non-executable mode. Here the file properties on my raspberry pi:

pi@raspberrypi:/opt/openhab/userdata/tmp/libNRJavaSerial_openhab_0 $ ls -l
insgesamt 76
-rw-r--r-- 1 openhab spi 76928 Mai 10 15:03 libNRJavaSerial.so

**Comment by cniweb** [comment] 2017-05-11 08:25
OK, can you change the rights and try again?

**Comment by stephan-bury** [comment] 2017-05-12 06:40
This is only possible in the Java code which is extracting the binary. It is extracted, when the class is instantiated, so the first time the RXTX driver is loaded. It has to be fixed in java code or JVM parameters, I would guess.

**Comment by stephan-bury** [comment] 2017-05-15 05:48
I made this change locally (but could not test it yet) - I'm not sure if this helps:

Date: Mon, 15 May 2017 07:40:50 +0200
Subject: [PATCH] Added executable flag on extracted library

---
 src/main/java/gnu/io/NativeResource.java | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/main/java/gnu/io/NativeResource.java b/src/main/java/gnu/io/NativeResource.java
index 93cba44..7b8267d 100644
--- a/src/main/java/gnu/io/NativeResource.java
+++ b/src/main/java/gnu/io/NativeResource.java
@@ -220,6 +220,7 @@ public class NativeResource {
 			throw new NativeResourceException("Unable to deploy native resource");
 		}
 		//System.out.println("Local file: "+fd.getAbsolutePath());
+		fd.setExecutable(true, false);
 		return fd;
 	}
 	
-- 
2.9.0.windows.1

**Comment by stephan-bury** [comment] 2017-05-15 20:56
This did not help - the file mode is still the same

**Comment by stephan-bury** [comment] 2017-05-16 07:26
I made it run yesterday evening with the following additional parameter in docker run command:
-e EXTRA_JAVA_OPTS="-Dos.arch=arm -Dsun.arch.abi=gnueabihf"

The problem are different system properties in the different VMs.

**Comment by stephan-bury** [comment] 2017-06-03 15:04
@peterjwood: will you include these java properties in the docker image as default options? I think the problem is solved?

**Comment by dawean** [comment] 2017-07-14 12:38
I got a similar error when installing Telldus Core gateway from paper UI. That libjnidispatch.so is missing
Changing Java to Java HotSpot (Oracle) solved the issue. 
If you extract jna-4.0.0.jar you find different libjnidispatch.so for different architectures. (jna-4.0.0\com\sun\jna\..) but not for aarch32hf
My guess is that java tries to find the .so file for aarch32hf instead of arm. 
Setting Dos.arch=arm maybe solves mine issue also.
I will have it a try later

**Comment by dawean** [comment] 2017-07-25 09:22
Setting Dos.arch=arm worked for me.

**Closed** 2017-09-14 20:57 UTC
Labels: help wanted
